"""Responsive layout defaults for lightweight Tkinter calculator surfaces."""

TABLE_GRID_COLOR = "#c4ccd4"
TABLE_HEADER_BG = "#e8edf2"
TABLE_EDITABLE_BG = "#ffffff"
TABLE_SELECTED_BG = "#dbeafe"
TABLE_ACTIVE_BG = "#bfdbfe"
TABLE_STATIC_BG = "#f1f3f5"
TABLE_HEADER_FG = "#26333f"
TABLE_STATIC_FG = "#66737f"
TABLE_INVALID_BG = "#fee2e2"
TABLE_PASS_BG = "#dcfce7"
RESULT_TITLE_BG = "#f1f3f5"
RESULT_HEADER_BG = "#e8edf2"
RESULT_VALUE_BG = "#ffffff"
RESULT_STATUS_FG = "#52606d"

TABLE_FONT_SIZE = 11
TABLE_BODY_FONT = ("TkDefaultFont", TABLE_FONT_SIZE)
TABLE_HEADER_FONT = ("TkDefaultFont", TABLE_FONT_SIZE, "bold")
TABLE_ROW_HEADER_CHARS = 12
TABLE_DATA_COLUMN_CHARS = 12
TABLE_ROW_HEADER_WEIGHT = 2
TABLE_DATA_COLUMN_WEIGHT = 3
TABLE_CELL_PADX = 8
TABLE_CELL_PADY = 4
TABLE_HEADER_PADY = 4
ISO_SECTION_PADX = 10
ISO_SECTION_BLOCK_GAP = 8
TABLE_SECTION_BREAK_GAP = 6

BATCH_MATRIX_CASE_COLUMN_WIDTH_CHARS = 6
BATCH_MATRIX_ROW_TYPE_COLUMN_WIDTH_CHARS = 10
BATCH_MATRIX_POINT_WIDTH_CHARS = 12
BATCH_MATRIX_RESULT_PRIMARY_WIDTH_CHARS = 10
BATCH_MATRIX_RESULT_SECONDARY_WIDTH_CHARS = 11
BATCH_MATRIX_RESULT_SOURCE_WIDTH_CHARS = 12
BATCH_DIALOG_SAFETY_MIN_SIZE = (640, 320)

CONTROL_NUMERIC_ENTRY_WIDTH_CHARS = 10
CONTROL_APPLIANCE_TYPE_SELECTOR_WIDTH_CHARS = 12
CONTROL_EQUIPMENT_TYPE_SELECTOR_WIDTH_CHARS = 6
CONTROL_REGION_CODE_SELECTOR_WIDTH_CHARS = 5
CONTROL_DETAIL_SERIES_SELECTOR_WIDTH_CHARS = 18

APP_WINDOW_SCREEN_MARGIN_X_RATIO = 0.06
APP_WINDOW_SCREEN_MARGIN_Y_RATIO = 0.08
APP_WINDOW_PREFERRED_WIDTH_RATIO = 0.66
APP_WINDOW_MAX_WIDTH_RATIO = 0.82
APP_WINDOW_MAX_HEIGHT_RATIO = 0.80
APP_WINDOW_FALLBACK_MIN_WIDTH = 640
APP_WINDOW_FALLBACK_MIN_HEIGHT = 480
APP_WINDOW_MIN_VISIBLE_WIDTH = 1
APP_WINDOW_MIN_VISIBLE_HEIGHT = 1
APP_WINDOW_CONTENT_SAFETY_MARGIN_RATIO = 0.05
