"""Responsive layout defaults for lightweight Tkinter calculator surfaces."""

from ui_common.visual_tokens import visual_color


TABLE_GRID_COLOR = visual_color("border.default")
TABLE_HEADER_BG = visual_color("table.header")
TABLE_EDITABLE_BG = visual_color("table.input")
TABLE_SELECTED_BG = visual_color("table.selected")
TABLE_ACTIVE_BG = visual_color("table.active")
TABLE_STATIC_BG = visual_color("table.fixed")
TABLE_HEADER_FG = visual_color("text.default")
TABLE_STATIC_FG = visual_color("text.muted")
TABLE_INVALID_BG = visual_color("table.invalid")
TABLE_PASS_BG = visual_color("table.result")
RESULT_TITLE_BG = visual_color("surface.header")
RESULT_HEADER_BG = visual_color("table.header")
RESULT_VALUE_BG = visual_color("surface.panel")
RESULT_STATUS_FG = visual_color("status.neutral")
TOP_NOTEBOOK_SELECTED_FG = visual_color("accent.primary")

TABLE_FONT_SIZE = 10
TABLE_BODY_FONT = ("TkDefaultFont", TABLE_FONT_SIZE)
TABLE_HEADER_FONT = ("TkDefaultFont", TABLE_FONT_SIZE, "bold")
TABLE_ROW_HEADER_CHARS = 12
TABLE_DATA_COLUMN_CHARS = 12
TABLE_ROW_HEADER_WEIGHT = 2
TABLE_DATA_COLUMN_WEIGHT = 3
TABLE_CELL_PADX = 8
TABLE_CELL_PADY = 4
TABLE_HEADER_PADY = 4
ISO_SECTION_PADX = 10
ISO_SECTION_BLOCK_GAP = 8
TABLE_SECTION_BREAK_GAP = 6

BATCH_MATRIX_CASE_COLUMN_WIDTH_CHARS = 6
BATCH_MATRIX_ROW_TYPE_COLUMN_WIDTH_CHARS = 10
BATCH_MATRIX_POINT_WIDTH_CHARS = 12
BATCH_MATRIX_RESULT_PRIMARY_WIDTH_CHARS = 10
BATCH_MATRIX_RESULT_SECONDARY_WIDTH_CHARS = 11
BATCH_MATRIX_RESULT_SOURCE_WIDTH_CHARS = 12
BATCH_DIALOG_SAFETY_MIN_SIZE = (640, 320)
BATCH_INPUT_BUTTON_TEXT = "일괄 입력"

CONTROL_NUMERIC_ENTRY_WIDTH_CHARS = 10
CONTROL_APPLIANCE_TYPE_SELECTOR_WIDTH_CHARS = 12
CONTROL_EQUIPMENT_TYPE_SELECTOR_WIDTH_CHARS = 6
CONTROL_REGION_CODE_SELECTOR_WIDTH_CHARS = 5
CONTROL_DETAIL_SERIES_SELECTOR_WIDTH_CHARS = 18

METRIC_TABLE_COMPACT_ROW_HEADER_CHARS = 8
METRIC_TABLE_DECLARED_DATA_COLUMN_CHARS = 8
METRIC_TABLE_STANDARD_DATA_COLUMN_CHARS = 10
METRIC_TABLE_EN14825_ROW_HEADER_CHARS = 22
METRIC_TABLE_DESCRIPTIVE_ROW_HEADER_CHARS = 18
METRIC_TABLE_POINT_DATA_COLUMN_CHARS = 14
METRIC_TABLE_ANCHOR_DATA_COLUMN_CHARS = 18
METRIC_TABLE_HEATING_DATA_COLUMN_CHARS = 12

RESULT_COMPARISON_VALUE_COLUMN_WIDTH_PX = TABLE_DATA_COLUMN_CHARS * 9
RESULT_COMPARISON_VALUE_COLUMN_MIN_WIDTH_PX = 80
RESULT_PROFILE_COLUMN_WIDTH_PX = 150
RESULT_PROFILE_COLUMN_MIN_WIDTH_PX = 120
RESULT_SCENARIO_COLUMN_WIDTH_PX = 180
RESULT_SCENARIO_COLUMN_MIN_WIDTH_PX = 150
BRAZIL_CSPF_RESULT_TABLE_HEIGHT = 2
BRAZIL_CSPF_RULE_COLUMN_WIDTHS_PX = (70, 240, 90, 90, 70)
ISO_SECTION_CONTENT_PAD = 4

DETAIL_GRAPH_BG = "white"
DETAIL_GRAPH_BORDER_COLOR = "gray80"
DETAIL_GRAPH_AXIS_FG = "gray25"
DETAIL_GRAPH_GRID_FG = "gray35"
DETAIL_GRAPH_SERIES_FG = "blue"

CONTROL_ROW_PADY = 6
CONTROL_LABEL_GAP = 4
CONTROL_GROUP_GAP = 10
CONTROL_COMPACT_GAP = 3

APP_WINDOW_SCREEN_MARGIN_X_RATIO = 0.06
APP_WINDOW_SCREEN_MARGIN_Y_RATIO = 0.08
APP_WINDOW_PREFERRED_WIDTH_RATIO = 0.66
APP_WINDOW_MAX_WIDTH_RATIO = 0.82
APP_WINDOW_MAX_HEIGHT_RATIO = 0.80
APP_WINDOW_FALLBACK_MIN_WIDTH = 640
APP_WINDOW_FALLBACK_MIN_HEIGHT = 480
APP_WINDOW_MIN_VISIBLE_WIDTH = 1
APP_WINDOW_MIN_VISIBLE_HEIGHT = 1
APP_WINDOW_CONTENT_SAFETY_MARGIN_RATIO = 0.05
