"""Local layout contracts for the lightweight Tkinter calculator surfaces."""

MATRIX_ROW_HEADER_WIDTH = 112
MATRIX_DATA_COLUMN_WIDTH = 150
ISO_SECTION_DATA_COLUMNS = 2
ISO_SECTION_CONTENT_WIDTH = (
    MATRIX_ROW_HEADER_WIDTH + MATRIX_DATA_COLUMN_WIDTH * ISO_SECTION_DATA_COLUMNS
)
ISO_SECTION_PADX = 10
ISO_SECTION_BLOCK_GAP = 8
