"""Responsive layout defaults for lightweight Tkinter calculator surfaces."""

TABLE_GRID_COLOR = "#c4ccd4"
TABLE_HEADER_BG = "#e8edf2"
TABLE_EDITABLE_BG = "#ffffff"
TABLE_SELECTED_BG = "#dbeafe"
TABLE_ACTIVE_BG = "#bfdbfe"
TABLE_STATIC_BG = "#f1f3f5"
TABLE_HEADER_FG = "#26333f"
TABLE_STATIC_FG = "#66737f"
RESULT_TITLE_BG = "#f1f3f5"
RESULT_HEADER_BG = "#e8edf2"
RESULT_VALUE_BG = "#ffffff"
RESULT_STATUS_FG = "#52606d"

TABLE_FONT_SIZE = 11
TABLE_BODY_FONT = ("TkDefaultFont", TABLE_FONT_SIZE)
TABLE_HEADER_FONT = ("TkDefaultFont", TABLE_FONT_SIZE, "bold")
TABLE_ROW_HEADER_CHARS = 12
TABLE_DATA_COLUMN_CHARS = 12
TABLE_ROW_HEADER_WEIGHT = 2
TABLE_DATA_COLUMN_WEIGHT = 3
TABLE_CELL_PADX = 8
TABLE_CELL_PADY = 4
TABLE_HEADER_PADY = 4
ISO_SECTION_PADX = 10
ISO_SECTION_BLOCK_GAP = 8
