"""Compact Markdown renderer for the codebase reference map."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import List

from .analyzer import (
    AnalysisResult,
    DuplicateGroup,
    HotspotFile,
    ImportEdge,
    KeywordHitGroup,
    LayerOverview,
)
from .metadata import render_metadata_comment


def _render_header(task_number: str | None = None) -> List[str]:
    lines: List[str] = []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines.append(f"# Codebase Reference Map\n")
    if task_number:
        lines.append(f"> Generated by code_checker on {now} (task {task_number}).\n")
    else:
        lines.append(f"> Generated by code_checker on {now}.\n")
    lines.append(
        "> **Caveat:** This map is evidence, not source of truth. "
        "Canonical rules live in `AGENTS.md`, `docs/architecture/`, and `docs/WORK_PLAN.md`.\n"
    )
    lines.append(
        "> Update this map after significant architectural changes or before large migrations.\n"
    )
    return lines


def _render_layer_overview(overviews: List[LayerOverview]) -> List[str]:
    lines: List[str] = []
    lines.append("## Layer Overview\n")
    lines.append("| Layer | Files | Total LOC |")
    lines.append("|-------|-------|-----------|")
    for lo in overviews:
        lines.append(f"| {lo.name} | {lo.file_count} | {lo.total_loc} |")
    lines.append("")
    return lines


def _render_keyword_groups(groups: List[KeywordHitGroup]) -> List[str]:
    lines: List[str] = []
    lines.append("## Keyword Hit Groups\n")
    lines.append(
        "> These are search cues based on file paths and top-level symbol names, "
        "not ownership declarations.\n"
    )
    for kg in groups:
        lines.append(f"### {kg.keyword}")
        shown = kg.files[:5]
        for f in shown:
            lines.append(f"- {f}")
        if len(kg.files) > 5:
            lines.append(f"- ... and {len(kg.files) - 5} more files")
        lines.append("")
    if not groups:
        lines.append("No keyword hit groups detected.\n")
    return lines


def _render_hotspots(title: str, hotspots: List[HotspotFile]) -> List[str]:
    lines: List[str] = []
    lines.append(f"## {title}\n")
    lines.append("| File | LOC | Classes | Long Functions |")
    lines.append("|------|-----|---------|--------------|")
    for h in hotspots:
        long_funcs = ", ".join(f"{n}({l})" for n, l in h.long_functions) or "-"
        lines.append(f"| {h.path} | {h.loc} | {h.class_count} | {long_funcs} |")
    lines.append("")
    return lines


def _render_duplicates(duplicates: List[DuplicateGroup]) -> List[str]:
    lines: List[str] = []
    lines.append("## Duplicate / Adjacent Helpers\n")
    lines.append(
        "> Top-level functions, classes, and constants appearing in multiple files "
        "(candidates for extraction or consolidation).\n"
    )
    lines.append(
        "> Framework methods (e.g. `grid`, `pack`, `data`, `keyPressEvent`) are filtered out.\n"
    )
    top_duplicates = duplicates[:20]
    for dg in top_duplicates:
        locs = ", ".join(f"{p}:{l}" for p, l in dg.locations)
        lines.append(f"- `{dg.name}`: {locs}")
    if len(duplicates) > 20:
        lines.append(f"- ... and {len(duplicates) - 20} more")
    if not duplicates:
        lines.append("No duplicate symbol candidates found.\n")
    lines.append("")
    return lines


def _render_import_edges(edges: List[ImportEdge]) -> List[str]:
    lines: List[str] = []
    lines.append("## Import Edges\n")
    lines.append("> Key cross-module imports (source -> imported module prefix).\n")
    seen: set = set()
    displayed = 0
    max_edges = 40
    for edge in edges:
        key = (edge.source, edge.target)
        if key in seen:
            continue
        seen.add(key)
        if displayed < max_edges:
            lines.append(f"- `{edge.source}` -> `{edge.target}`")
            displayed += 1
    if len(edges) > max_edges:
        lines.append(f"- ... and {len(edges) - max_edges} more")
    if not edges:
        lines.append("No import edges recorded.\n")
    lines.append("")
    return lines


def _render_usage() -> List[str]:
    lines: List[str] = []
    lines.append("## How to Use Before Implementation\n")
    lines.append("1. Search this map for existing symbols matching your intent.")
    lines.append("2. Check the Active Hotspots list before adding responsibility to a soft-limit file.")
    lines.append("3. Review Import Edges to ensure layer-boundary compliance.")
    lines.append("4. If a symbol already exists, prefer reuse; if not reusable, document the reason.")
    lines.append("")
    return lines


def render_compact_map(
    result: AnalysisResult,
    task_number: str | None = None,
    metadata: dict[str, str | bool] | None = None,
) -> str:
    lines: List[str] = []
    if metadata:
        lines.append(render_metadata_comment(metadata))
    lines.extend(_render_header(task_number))
    lines.extend(_render_layer_overview(result.layer_overviews))
    lines.extend(_render_keyword_groups(result.keyword_hit_groups))
    lines.extend(_render_hotspots("Active Hotspots", result.active_hotspots))
    lines.extend(_render_hotspots("Legacy / Deferred Hotspots", result.legacy_hotspots))
    lines.extend(_render_duplicates(result.duplicates))
    lines.extend(_render_import_edges(result.import_edges))
    lines.extend(_render_usage())
    return "\n".join(lines)
