"""Compact Markdown renderer for the codebase reference map."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import List

from .analyzer import (
    AnalysisResult,
    DuplicateGroup,
    HotspotFile,
    ImportEdge,
    LayerOverview,
    OwnerGroup,
)


def render_compact_map(result: AnalysisResult, task_number: str = "271") -> str:
    lines: List[str] = []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines.append(f"# Codebase Reference Map\n")
    lines.append(f"> Generated by code_checker MVP on {now} (task {task_number}).\n")
    lines.append(
        "> **Caveat:** This map is evidence, not source of truth. "
        "Canonical rules live in `AGENTS.md`, `docs/architecture/`, and `docs/WORK_PLAN.md`.\n"
    )
    lines.append(
        "> Update this map after significant architectural changes or before large migrations.\n"
    )

    # Layer Overview
    lines.append("## Layer Overview\n")
    lines.append("| Layer | Files | Total LOC |")
    lines.append("|-------|-------|-----------|")
    for lo in result.layer_overviews:
        lines.append(f"| {lo.name} | {lo.file_count} | {lo.total_loc} |")
    lines.append("")

    # Owner Groups
    lines.append("## Owner Groups\n")
    for og in result.owner_groups:
        lines.append(f"### {og.keyword}")
        shown = og.files[:5]
        for f in shown:
            lines.append(f"- {f}")
        if len(og.files) > 5:
            lines.append(f"- ... and {len(og.files) - 5} more files")
        lines.append("")
    if not result.owner_groups:
        lines.append("No owner groups detected.\n")

    # Hotspot Files
    lines.append("## Hotspot Files\n")
    lines.append("| File | LOC | Classes | Long Functions |")
    lines.append("|------|-----|---------|--------------|")
    for h in result.hotspots:
        long_funcs = ", ".join(f"{n}({l})" for n, l in h.long_functions) or "-"
        lines.append(f"| {h.path} | {h.loc} | {h.class_count} | {long_funcs} |")
    lines.append("")

    # Duplicate / Adjacent Helpers
    lines.append("## Duplicate / Adjacent Helpers\n")
    lines.append(
        "> Symbols appearing in multiple files (candidates for extraction or consolidation).\n"
    )
    top_duplicates = result.duplicates[:20]
    for dg in top_duplicates:
        locs = ", ".join(f"{p}:{l}" for p, l in dg.locations)
        lines.append(f"- `{dg.name}`: {locs}")
    if len(result.duplicates) > 20:
        lines.append(f"- ... and {len(result.duplicates) - 20} more")
    if not result.duplicates:
        lines.append("No duplicate symbol candidates found.\n")
    lines.append("")

    # Import Edges
    lines.append("## Import Edges\n")
    lines.append("> Key cross-module imports (source -> top-level module).\n")
    seen: set = set()
    displayed = 0
    max_edges = 40
    for edge in result.import_edges:
        key = (edge.source, edge.target)
        if key in seen:
            continue
        seen.add(key)
        if displayed < max_edges:
            lines.append(f"- `{edge.source}` -> `{edge.target}`")
            displayed += 1
    if len(result.import_edges) > max_edges:
        lines.append(f"- ... and {len(result.import_edges) - max_edges} more")
    if not result.import_edges:
        lines.append("No import edges recorded.\n")
    lines.append("")

    # How to use
    lines.append("## How to Use Before Implementation\n")
    lines.append("1. Search this map for existing symbols matching your intent.")
    lines.append("2. Check the Hotspot Files list before adding responsibility to a soft-limit file.")
    lines.append("3. Review Import Edges to ensure layer-boundary compliance.")
    lines.append("4. If a symbol already exists, prefer reuse; if not reusable, document the reason.")
    lines.append("")

    return "\n".join(lines)
