"""Surface protocol for common Tk table interaction controllers."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Protocol

from ui_tk.table.interaction_core import CellAddress
from ui_tk.table.roles import CellRole

TableSnapshot = object


class TkTableSurface(Protocol):
    """Small surface contract implemented by Tk table adapters."""

    def row_count(self) -> int: ...
    def column_count(self) -> int: ...
    def cell_roles(self) -> tuple[CellRole, ...]: ...
    def ensure_row_count(self, count: int) -> None: ...
    def text_at_position(self, position: CellAddress) -> str: ...
    def set_positions_batch(self, values: Mapping[CellAddress, str]) -> bool: ...
    def snapshot(self) -> TableSnapshot: ...
    def restore_snapshot(self, snapshot: TableSnapshot) -> None: ...
    def cell_frame(self, position: CellAddress): ...
    def cell_widget(self, position: CellAddress): ...
    def focus_widget(self, position: CellAddress): ...
    def default_cell_background(self, position: CellAddress) -> str: ...
    def clipboard_clear(self) -> None: ...
    def clipboard_append(self, text: str) -> None: ...
    def clipboard_get(self) -> str: ...
    def winfo_containing(self, root_x: int, root_y: int): ...
